version: 0.1.0.{build}
image: Visual Studio 2015

skip_commits:
  message: \[(ci skip|skip ci)\].*

before_build:
  - .paket\paket.bootstrapper.exe
  - .paket\paket.exe restore

test_script:
  - ps: .\RunTests.ps1
